### ISSUE TITLE
KeyError: 'nonce'

### ISSUE THREAD

**Issue by cjuwen** [ReZeroS/weibo-prize#4]
Traceback (most recent call last):
  File "weibo.py", line 120, in <module>
    cookies = login.get_cookies(user_name, pass_word)
  File "/root/weibo-prize/login.py", line 96, in get_cookies
    cookies = weibo_login.login()
  File "/root/weibo-prize/login.py", line 85, in login
    nonce, pubkey, rsakv = self.pre_login()
  File "/root/weibo-prize/login.py", line 50, in pre_login
    nonce = pre_data_dict['nonce']
KeyError: 'nonce'
作者大大，这个问题可以解决吗？

**Comment by ReZeroS** [comment]
@cjuwen 项目已经三年了，估计weibo也变了登陆的一些防护，不再折腾了老哥你有兴趣的话自己研究下吧，报错这个应该是登陆页面的第一个接口，你可以对比下request参数的不同

**Comment by cjuwen** [comment]
好的，谢谢老哥
